version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development

    volumes:
      - ./backend:/app:delegated
      - /app/node_modules
    restart: on-failure
    command: sh -c "npm start"

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
